# Generated by Django 4.2 on 2024-08-01 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EvaFirst', '0008_applications_applicants_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applications',
            name='Applicants_email',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='applications',
            name='Applicants_mob',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='postjob',
            name='job_role',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
