# Generated by Django 4.2 on 2024-08-02 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EvaFirst', '0010_alter_postjob_recruiter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentprofile',
            name='mark',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='passing_year',
            field=models.CharField(blank=True, default='', max_length=80, null=True),
        ),
    ]
