# Generated by Django 4.2 on 2024-08-05 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EvaFirst', '0012_alter_studentprofile_profile_picture_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='managerprofile',
            name='manager_Firstname',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='managerprofile',
            name='manager_Lastname',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='managerprofile',
            name='manager_email',
            field=models.EmailField(blank=True, max_length=100, null=True),
        ),
    ]
