# Generated by Django 4.2 on 2024-08-05 21:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('EvaFirst', '0015_alter_applications_applyed_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='applications',
            name='applyed_at',
        ),
        migrations.RemoveField(
            model_name='managerprofile',
            name='created_time',
        ),
        migrations.RemoveField(
            model_name='postjob',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='recruiterprofile',
            name='created_time',
        ),
        migrations.RemoveField(
            model_name='studentprofile',
            name='created_time',
        ),
    ]
