# Generated by Django 4.2 on 2024-08-05 21:35

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('EvaFirst', '0017_postjob_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='applications',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
