# Generated by Django 4.2 on 2024-08-06 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EvaFirst', '0020_alter_recruiterprofile_company_location_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='postjob',
            name='Sector',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
    ]
