# Generated by Django 4.2 on 2024-08-08 12:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('EvaFirst', '0022_applications_applystd_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='applications',
            name='applyStd_id',
        ),
    ]
