# Generated by Django 4.2 on 2024-08-08 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EvaFirst', '0023_remove_applications_applystd_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postjob',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
