# Generated by Django 4.2 on 2024-08-08 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EvaFirst', '0024_alter_postjob_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postjob',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
