# Generated by Django 4.2 on 2024-08-08 16:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('EvaFirst', '0025_alter_postjob_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='applications',
            old_name='jobpostInfo',
            new_name='jobpostInfoFK',
        ),
    ]
