# Generated by Django 4.2 on 2024-08-09 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EvaFirst', '0026_rename_jobpostinfo_applications_jobpostinfofk'),
    ]

    operations = [
        migrations.AddField(
            model_name='applications',
            name='postId',
            field=models.IntegerField(default=0),
        ),
    ]
